workflows:
  ios-release:
    name: iOS Release Workflow
    environment:
      flutter: stable
      xcode: latest
      groups:
        - appstore_credentials
        - codemagic_apple_credentials   # подключается автоматическая подпись
    scripts:
      - name: Clean project
        script: flutter clean

      - name: Install dependencies
        script: flutter pub get

      - name: Build IPA with automatic code signing
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
