workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      groups:
        - appstore_credentials
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean project
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Install pods
        script: |
          cd ios
          pod install
      - name: Build and archive
        script: |
          flutter build ios --release --no-codesign
          cd ios
          xcodebuild -workspace Artrit.xcworkspace -scheme RunnArtriter -configuration Release archive -archivePath build/Artrit.xcarchive
      - name: Export IPA
        script: |
          cd ios
          xcodebuild -exportArchive -archivePath build/Artrit.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/ipa
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true