version: 1.0.1+9  # Увеличиваем номер сборки до 7
workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: 16.0  # Последняя стабильная версия Xcode
      groups:
        - appstore_credentials
        - signing
    scripts:
      - name: Verify Xcode version
        script: |
          xcodebuild -version
      - name: Clean and install dependencies
        script: |
          flutter clean
          flutter pub get
          cd ios
          xcodebuild clean -project Runner.xcodeproj -scheme Runner -configuration Release
      - name: Build signed IPA with SwiftSupport
        script: |
          flutter build ios --release --no-codesign --build-number=7
          xcode-project build-ipa \
            --project ios/Runner.xcodeproj \
            --scheme Runner \
            --config Release \
            --archive-path build/ios/archive/Runner.xcarchive \
            --export-options-plist ios/exportOptions.plist
      - name: Verify SwiftSupport
        script: |
          echo "Checking for SwiftSupport in IPA..."
          unzip -l build/ios/ipa/*.ipa | grep SwiftSupport || echo "SwiftSupport not found"
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/Runner.xcarchive
    publishing:
      app_store_connect:
        auth: api_key
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true