version: 1.0.1+11  # Увеличиваем номер сборки
workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: 16.0
      groups:
        - appstore_credentials
        - signing
    scripts:
      - name: Verify Xcode version
        script: |
          xcodebuild -version

      - name: Clean and install dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Build signed IPA
        script: |
          flutter build ipa --release --build-number=9

      - name: Verify SwiftSupport
        script: |
          echo "Checking for SwiftSupport in IPA..."
          unzip -l build/ios/ipa/*.ipa | grep SwiftSupport || echo "❌ SwiftSupport not found"

    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: api_key
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
