workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      groups:
        - appstore_credentials
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
      - name: Build IPA
        script: |
          xcode-project build-ipa --workspace "Artrit.xcworkspace" --scheme "Artrit"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true