version: 1.0.1+4
workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
      groups:
        - appstore_credentials
        - signing
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build signed IPA
        script: flutter build ipa
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: api_key
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
        post_clone:
          - name: Add NSPhotoLibraryUsageDescription to Info.plist
            script: |
              plutil -insert NSPhotoLibraryUsageDescription -string "Это нужно для отправки изображений в чат." ios/Runner/Info.plist
        post_build:
          - name: Ensure Swift libraries are embedded
            script: |
              echo "Ensuring SwiftSupport is embedded..."
              defaults write com.apple.dt.Xcode AlwaysEmbedSwiftStandardLibraries -bool YES || true